In [ ]:
import pandas as pd
import numpy as np

In [3]:
cpcb_2024 = pd.read_csv("../data/raw/CPCB/Raw_Data_2024_site_5792_ambazari_nagpur_mpcb_1Hr.csv")

cpcb_2025 = pd.read_csv("../data/raw/CPCB/Raw_Data_2025_site_5792_ambazari_nagpur_mpcb_1Hr.csv")

weather = pd.read_csv("../data/raw/Weather/open-meteo-21.12N79.02E323m.csv", skiprows=2)

In [5]:
cpcb_2024["Timestamp"] = pd.to_datetime(cpcb_2024["Timestamp"])
cpcb_2025["Timestamp"] = pd.to_datetime(cpcb_2025["Timestamp"])
weather["time"] = pd.to_datetime(weather["time"])

In [ ]:
cpcb_columns = [
    "Timestamp",
    "PM2.5 (µg/m³)",
    "PM10 (µg/m³)",
    "NO2 (µg/m³)",
    "SO2 (µg/m³)",
    "CO (mg/m³)",
    "Ozone (µg/m³)",
    "AT (°C)",
    "RH (%)",
    "WS (m/s)",
    "WD (deg)",
    "RF (mm)",
    "SR (W/mt2)"
]

cpcb_2024_clean = cpcb_2024[cpcb_columns].copy()
cpcb_2025_clean = cpcb_2025[cpcb_columns].copy()

In [7]:
rename_columns = {
    "Timestamp": "timestamp",
    "PM2.5 (µg/m³)": "pm25",
    "PM10 (µg/m³)": "pm10",
    "NO2 (µg/m³)": "no2",
    "SO2 (µg/m³)": "so2",
    "CO (mg/m³)": "co",
    "Ozone (µg/m³)": "o3",
    "AT (°C)": "temperature",
    "RH (%)": "humidity",
    "WS (m/s)": "wind_speed",
    "WD (deg)": "wind_direction",
    "RF (mm)": "rainfall",
    "SR (W/mt2)": "solar_radiation"
}

cpcb_2024_clean = cpcb_2024_clean.rename(columns=rename_columns)
cpcb_2025_clean = cpcb_2025_clean.rename(columns=rename_columns)

In [9]:
print(cpcb_2024_clean.columns.tolist())
print(cpcb_2024_clean.shape)

print(cpcb_2025_clean.columns.tolist())
print(cpcb_2025_clean.shape)

['timestamp', 'pm25', 'pm10', 'no2', 'so2', 'co', 'o3', 'temperature', 'humidity', 'wind_speed', 'wind_direction', 'rainfall', 'solar_radiation']
(8784, 13)
['timestamp', 'pm25', 'pm10', 'no2', 'so2', 'co', 'o3', 'temperature', 'humidity', 'wind_speed', 'wind_direction', 'rainfall', 'solar_radiation']
(8760, 13)

In [10]:
numeric_columns = [
    "pm25",
    "pm10",
    "no2",
    "so2",
    "co",
    "o3",
    "temperature",
    "humidity",
    "wind_speed",
    "wind_direction",
    "rainfall",
    "solar_radiation"
]

print("Negative values — CPCB 2024")
print((cpcb_2024_clean[numeric_columns] < 0).sum())

print("\nNegative values — CPCB 2025")
print((cpcb_2025_clean[numeric_columns] < 0).sum())

Negative values — CPCB 2024
pm25               0
pm10               0
no2                0
so2                0
co                 0
o3                 0
temperature        0
humidity           0
wind_speed         0
wind_direction     0
rainfall           0
solar_radiation    0
dtype: int64

Negative values — CPCB 2025
pm25               0
pm10               0
no2                0
so2                0
co                 0
o3                 0
temperature        0
humidity           0
wind_speed         0
wind_direction     0
rainfall           0
solar_radiation    0
dtype: int64

In [11]:
cpcb_2024_clean[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
pm25,8707.0,47.716754,28.266188,0.05,25.3300,43.040,65.650,487.48
pm10,8696.0,98.291293,47.413807,9.26,64.7275,92.150,123.035,832.54
no2,8688.0,22.664663,21.098552,0.01,9.6400,16.115,27.545,177.75
so2,8690.0,16.823023,18.102683,0.34,7.5800,11.760,19.020,196.56
co,8707.0,0.693162,0.579615,0.00,0.3600,0.520,0.780,7.63
o3,8563.0,38.815704,34.485494,0.01,10.0800,28.940,59.170,187.86
temperature,8700.0,26.378663,5.759311,8.54,23.2875,25.950,29.760,45.56
humidity,8691.0,68.907610,19.748224,19.21,53.3000,71.240,86.140,98.35
wind_speed,8698.0,0.998305,0.313058,0.12,0.7800,1.020,1.240,2.23
wind_direction,8700.0,225.362432,87.998189,0.01,162.3300,237.685,310.490,359.14
rainfall,8700.0,0.032548,0.322327,0.00,0.0000,0.000,0.000,12.60
solar_radiation,8700.0,100.778349,194.247434,0.00,0.0000,0.000,121.530,948.80

In [12]:
cpcb_2025_clean[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
pm25,8667.0,44.856177,26.082824,1.01,23.9250,40.600,61.6200,333.16
pm10,8673.0,84.477258,43.884124,6.19,48.3000,80.290,112.7600,391.03
no2,8640.0,19.470851,17.079937,0.01,8.4000,14.080,23.5825,134.30
so2,8634.0,17.011403,18.221134,0.02,8.4425,11.760,17.6875,198.76
co,8682.0,0.598640,0.501296,0.01,0.3000,0.440,0.6900,6.12
o3,8499.0,33.667877,30.777357,0.01,9.4050,23.370,48.7600,159.96
temperature,8696.0,25.682819,6.243661,9.04,22.8200,25.705,29.3600,43.27
humidity,8696.0,67.323638,22.742232,16.24,48.0350,70.280,87.4450,97.36
wind_speed,8696.0,0.997733,0.318305,0.14,0.7600,1.010,1.2500,4.34
wind_direction,8696.0,231.349495,86.134751,2.74,166.1925,249.405,310.6500,357.08
rainfall,8696.0,0.035043,0.349671,0.00,0.0000,0.000,0.0000,12.00
solar_radiation,8696.0,37.172870,66.049732,0.00,0.0000,0.000,52.7125,302.80

In [13]:
# Mean imputation
# Median imputation
# KNN imputation
# MICE / Iterative Imputation

print("Missing values — CPCB 2024")
print(cpcb_2024_clean.isnull().sum())

print("\nMissing values — CPCB 2025")
print(cpcb_2025_clean.isnull().sum())

Missing values — CPCB 2024
timestamp            0
pm25                77
pm10                88
no2                 96
so2                 94
co                  77
o3                 221
temperature         84
humidity            93
wind_speed          86
wind_direction      84
rainfall            84
solar_radiation     84
dtype: int64

Missing values — CPCB 2025
timestamp            0
pm25                93
pm10                87
no2                120
so2                126
co                  78
o3                 261
temperature         64
humidity            64
wind_speed          64
wind_direction      64
rainfall            64
solar_radiation     64
dtype: int64

In [ ]:
missing_summary_2024 = pd.DataFrame({"missing_count": cpcb_2024_clean.isnull().sum(), "missing_percentage": cpcb_2024_clean.isnull().mean() * 100})

missing_summary_2024 = missing_summary_2024.sort_values("missing_percentage", ascending=False)

missing_summary_2024

                 missing_count  missing_percentage
o3                         221            2.515938
no2                         96            1.092896
so2                         94            1.070128
humidity                    93            1.058743
pm10                        88            1.001821
wind_speed                  86            0.979053
wind_direction              84            0.956284
rainfall                    84            0.956284
temperature                 84            0.956284
solar_radiation             84            0.956284
pm25                        77            0.876594
co                          77            0.876594
timestamp                    0            0.000000

In [15]:
missing_summary_2025 = pd.DataFrame({ "missing_count": cpcb_2025_clean.isnull().sum(), "missing_percentage": cpcb_2025_clean.isnull().mean() * 100})

missing_summary_2025 = missing_summary_2025.sort_values( "missing_percentage", ascending=False)

missing_summary_2025

                 missing_count  missing_percentage
o3                         261            2.979452
so2                        126            1.438356
no2                        120            1.369863
pm25                        93            1.061644
pm10                        87            0.993151
co                          78            0.890411
wind_speed                  64            0.730594
temperature                 64            0.730594
humidity                    64            0.730594
rainfall                    64            0.730594
wind_direction              64            0.730594
solar_radiation             64            0.730594
timestamp                    0            0.000000

In [ ]:
target_pollutants = ["pm25", "pm10", "no2", "so2", "co", "o3"]

imputation_data = cpcb_2024_clean[target_pollutants].copy()

# Keep only rows where all six pollutants are originally available
complete_data = imputation_data.dropna().copy()

print("Original CPCB 2024 rows:", len(imputation_data))
print("Complete rows available for experiment:", len(complete_data))

Original CPCB 2024 rows: 8784
Complete rows available for experiment: 8429

In [17]:
from sklearn.model_selection import train_test_split

# Make a copy of the complete data
validation_data = complete_data.copy()

# Randomly hide 10% of the values
rng = np.random.default_rng(42)

mask = rng.random(validation_data.shape) < 0.10

masked_data = validation_data.mask(mask)

print("Total values:", validation_data.size)
print("Artificially hidden values:", mask.sum())
print("Remaining known values:", masked_data.notna().sum().sum())

Total values: 50574
Artificially hidden values: 4992
Remaining known values: 45582

In [19]:
mean_imputed = masked_data.copy()

for column in target_pollutants:
    mean_imputed[column] = mean_imputed[column].fillna(masked_data[column].mean())

In [20]:
median_imputed = masked_data.copy()

for column in target_pollutants:
    median_imputed[column] = median_imputed[column].fillna(masked_data[column].median())

In [21]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

results = []

for column in target_pollutants:

    # Only evaluate the values that we intentionally masked
    masked_positions = mask[:, target_pollutants.index(column)]

    actual = validation_data.loc[masked_positions, column]
    mean_pred = mean_imputed.loc[masked_positions, column]
    median_pred = median_imputed.loc[masked_positions, column]

    results.append({
        "pollutant": column,
        "mean_MAE": mean_absolute_error(actual, mean_pred),
        "mean_RMSE": np.sqrt(mean_squared_error(actual, mean_pred)),
        "median_MAE": mean_absolute_error(actual, median_pred),
        "median_RMSE": np.sqrt(mean_squared_error(actual, median_pred))
    })

results_df = pd.DataFrame(results)

results_df

  pollutant   mean_MAE  mean_RMSE  median_MAE  median_RMSE
0      pm25  22.076346  26.527376   21.762481    26.719520
1      pm10  37.076221  50.654035   36.989055    51.346255
2       no2  14.575674  21.105349   13.240879    22.038542
3       so2  10.873156  19.301657   10.042532    20.191077
4        co   0.384055   0.610914    0.340884     0.634473
5        o3  28.664563  35.095212   27.732867    36.676083

In [22]:
from sklearn.impute import KNNImputer

# Standardize the data because the pollutants have different scales
column_means = masked_data.mean()
column_stds = masked_data.std()

scaled_data = (masked_data - column_means) / column_stds

# KNN imputation
knn_imputer = KNNImputer(n_neighbors=5, weights="distance")

knn_array = knn_imputer.fit_transform(scaled_data)

# Convert back to DataFrame
knn_imputed_scaled = pd.DataFrame(
    knn_array,
    columns=target_pollutants,
    index=masked_data.index
)

# Convert back to original scale
knn_imputed = (
    knn_imputed_scaled * column_stds
) + column_means

knn_imputed.head()

     pm25    pm10    no2        so2        co         o3
5  108.17  172.20  21.37  11.960000  0.664722  17.510000
6  102.10  158.40  22.22  11.980000  0.560000  18.280000
7   88.31  147.01  25.92  11.290000  0.780000  36.558512
8   84.49  157.55  29.82  11.860000  0.930000  23.590000
9   83.77  163.40  36.90  26.977567  0.990000  57.730000

In [24]:
knn_results = []

for column in target_pollutants:

    # Positions that were intentionally masked
    masked_positions = mask[:, target_pollutants.index(column)]

    actual = validation_data.loc[validation_data.index[masked_positions], column]
    knn_pred = knn_imputed.loc[validation_data.index[masked_positions], column]

    knn_results.append({
        "pollutant": column,
        "knn_MAE": mean_absolute_error(actual, knn_pred),
        "knn_RMSE": np.sqrt(mean_squared_error(actual, knn_pred))
    })

knn_results_df = pd.DataFrame(knn_results)

knn_results_df

  pollutant    knn_MAE   knn_RMSE
0      pm25  14.377429  20.372169
1      pm10  27.227841  44.408904
2       no2  10.417311  16.415859
3       so2   9.831869  18.824065
4        co   0.274256   0.464597
5        o3  22.051048  30.031129

In [25]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

# Create MICE imputer
mice_imputer = IterativeImputer(
    random_state=42,
    max_iter=10
)

# Perform MICE imputation
mice_array = mice_imputer.fit_transform(masked_data)

# Convert to DataFrame
mice_imputed = pd.DataFrame(
    mice_array,
    columns=target_pollutants,
    index=masked_data.index
)

mice_imputed.head()

c:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\impute\_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

     pm25    pm10    no2        so2        co         o3
5  108.17  172.20  21.37  11.960000  0.922775  17.510000
6  102.10  158.40  22.22  11.980000  0.560000  18.280000
7   88.31  147.01  25.92  11.290000  0.780000  44.140575
8   84.49  157.55  29.82  11.860000  0.930000  23.590000
9   83.77  163.40  36.90  27.025165  0.990000  57.730000

In [26]:
mice_results = []

for column in target_pollutants:

    # Positions that were intentionally masked
    masked_positions = mask[:, target_pollutants.index(column)]

    actual = validation_data.loc[
        validation_data.index[masked_positions], column
    ]

    mice_pred = mice_imputed.loc[
        validation_data.index[masked_positions], column
    ]

    mice_results.append({
        "pollutant": column,
        "mice_MAE": mean_absolute_error(actual, mice_pred),
        "mice_RMSE": np.sqrt(mean_squared_error(actual, mice_pred))
    })

mice_results_df = pd.DataFrame(mice_results)

mice_results_df

  pollutant   mice_MAE  mice_RMSE
0      pm25  10.063969  14.978787
1      pm10  16.649789  30.167724
2       no2   8.267884  13.098747
3       so2   8.241946  16.149303
4        co   0.226239   0.382705
5        o3  22.083204  28.524621

In [27]:
#MICE (Multiple Imputation by Chained Equations) is selected as the primary imputation method for the pollutant variables because it achieved the lowest RMSE for all six pollutants and the lowest MAE for five of six pollutants in the controlled validation experiment.
final_comparison = results_df.merge(
    knn_results_df,
    on="pollutant"
).merge(
    mice_results_df,
    on="pollutant"
)

final_comparison

,pollutant,mean_MAE,mean_RMSE,median_MAE,median_RMSE,knn_MAE,knn_RMSE,mice_MAE,mice_RMSE
0,pm25,22.076346,26.527376,21.762481,26.719520,14.377429,20.372169,10.063969,14.978787
1,pm10,37.076221,50.654035,36.989055,51.346255,27.227841,44.408904,16.649789,30.167724
2,no2,14.575674,21.105349,13.240879,22.038542,10.417311,16.415859,8.267884,13.098747
3,so2,10.873156,19.301657,10.042532,20.191077,9.831869,18.824065,8.241946,16.149303
4,co,0.384055,0.610914,0.340884,0.634473,0.274256,0.464597,0.226239,0.382705
5,o3,28.664563,35.095212,27.732867,36.676083,22.051048,30.031129,22.083204,28.524621

In [28]:
# Create copies for final imputation
cpcb_2024_imputed = cpcb_2024_clean.copy()
cpcb_2025_imputed = cpcb_2025_clean.copy()

print("2024 shape:", cpcb_2024_imputed.shape)
print("2025 shape:", cpcb_2025_imputed.shape)

2024 shape: (8784, 13)
2025 shape: (8760, 13)

In [29]:
print("Missing values before MICE - 2024")
print(cpcb_2024_imputed[target_pollutants].isnull().sum())

print("\nMissing values before MICE - 2025")
print(cpcb_2025_imputed[target_pollutants].isnull().sum())

Missing values before MICE - 2024
pm25     77
pm10     88
no2      96
so2      94
co       77
o3      221
dtype: int64

Missing values before MICE - 2025
pm25     93
pm10     87
no2     120
so2     126
co       78
o3      261
dtype: int64

In [30]:
# MICE imputation for 2024
mice_imputer_2024 = IterativeImputer(
    random_state=42,
    max_iter=10
)

imputed_2024_array = mice_imputer_2024.fit_transform(
    cpcb_2024_imputed[target_pollutants]
)

cpcb_2024_imputed[target_pollutants] = imputed_2024_array

print("2024 missing values after MICE:")
print(cpcb_2024_imputed[target_pollutants].isnull().sum())

2024 missing values after MICE:
pm25    0
pm10    0
no2     0
so2     0
co      0
o3      0
dtype: int64

c:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\impute\_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [31]:
# MICE imputation for 2025
mice_imputer_2025 = IterativeImputer(
    random_state=42,
    max_iter=10
)

imputed_2025_array = mice_imputer_2025.fit_transform(
    cpcb_2025_imputed[target_pollutants]
)

cpcb_2025_imputed[target_pollutants] = imputed_2025_array

print("2025 missing values after MICE:")
print(cpcb_2025_imputed[target_pollutants].isnull().sum())

2025 missing values after MICE:
pm25    0
pm10    0
no2     0
so2     0
co      0
o3      0
dtype: int64

c:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\impute\_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [37]:
# Check missing values after MICE
print("2024 missing values:")
print(cpcb_2024_imputed[target_pollutants].isnull().sum())

print("\n2025 missing values:")
print(cpcb_2025_imputed[target_pollutants].isnull().sum())

# Check for negative values after MICE
print("\n2024 negative values:")
print((cpcb_2024_imputed[target_pollutants] < 0).sum())

print("\n2025 negative values:")
print((cpcb_2025_imputed[target_pollutants] < 0).sum())

2024 missing values:
pm25    0
pm10    0
no2     0
so2     0
co      0
o3      0
dtype: int64

2025 missing values:
pm25    0
pm10    0
no2     0
so2     0
co      0
o3      0
dtype: int64

2024 negative values:
pm25    0
pm10    0
no2     0
so2     0
co      0
o3      0
dtype: int64

2025 negative values:
pm25    0
pm10    0
no2     0
so2     0
co      0
o3      0
dtype: int64

In [34]:
print("Negative O3 values in 2024:")
print(cpcb_2024_imputed.loc[cpcb_2024_imputed["o3"] < 0, ["timestamp", "o3"]])

print("\nNegative O3 values in 2025:")
print(cpcb_2025_imputed.loc[cpcb_2025_imputed["o3"] < 0, ["timestamp", "o3"]])

Negative O3 values in 2024:
               timestamp         o3
1594 2024-03-07 10:00:00  -1.942622
1941 2024-03-21 21:00:00 -10.281894
1943 2024-03-21 23:00:00 -14.970333
1990 2024-03-23 22:00:00 -48.998646
2108 2024-03-28 20:00:00 -27.135609
3359 2024-05-19 23:00:00  -3.653952
4558 2024-07-08 22:00:00  -7.493084
4629 2024-07-11 21:00:00  -7.149615
4630 2024-07-11 22:00:00 -18.400787
4631 2024-07-11 23:00:00 -29.127438
5445 2024-08-14 21:00:00  -6.806517

Negative O3 values in 2025:
               timestamp         o3
43   2025-01-02 19:00:00 -12.373824
428  2025-01-18 20:00:00  -7.973595
479  2025-01-20 23:00:00  -8.265715
498  2025-01-21 18:00:00 -18.750236
523  2025-01-22 19:00:00 -43.408977
741  2025-01-31 21:00:00  -2.800120
763  2025-02-01 19:00:00 -16.291046
790  2025-02-02 22:00:00 -10.630568
813  2025-02-03 21:00:00  -1.788872
2565 2025-04-17 21:00:00 -14.904100
3164 2025-05-12 20:00:00 -91.017760
3165 2025-05-12 21:00:00 -42.761839
8759 2025-12-31 23:00:00 -10.586204

In [35]:
# Ensure pollutant concentrations cannot be negative
cpcb_2024_imputed[target_pollutants] = (
    cpcb_2024_imputed[target_pollutants].clip(lower=0)
)

cpcb_2025_imputed[target_pollutants] = (
    cpcb_2025_imputed[target_pollutants].clip(lower=0)
)

In [36]:
print("2024 negative values after correction:")
print((cpcb_2024_imputed[target_pollutants] < 0).sum())

print("\n2025 negative values after correction:")
print((cpcb_2025_imputed[target_pollutants] < 0).sum())

2024 negative values after correction:
pm25    0
pm10    0
no2     0
so2     0
co      0
o3      0
dtype: int64

2025 negative values after correction:
pm25    0
pm10    0
no2     0
so2     0
co      0
o3      0
dtype: int64

In [38]:
print("2024 duplicate timestamps:",
      cpcb_2024_imputed["timestamp"].duplicated().sum())

print("2025 duplicate timestamps:",
      cpcb_2025_imputed["timestamp"].duplicated().sum())

print("\n2024 date range:")
print(cpcb_2024_imputed["timestamp"].min(),
      "to",
      cpcb_2024_imputed["timestamp"].max())

print("\n2025 date range:")
print(cpcb_2025_imputed["timestamp"].min(),
      "to",
      cpcb_2025_imputed["timestamp"].max())

2024 duplicate timestamps: 0
2025 duplicate timestamps: 0

2024 date range:
2024-01-01 00:00:00 to 2024-12-31 23:00:00

2025 date range:
2025-01-01 00:00:00 to 2025-12-31 23:00:00

In [39]:
print("2024 shape:", cpcb_2024_imputed.shape)
print("2025 shape:", cpcb_2025_imputed.shape)

print("\n2024 data types:")
print(cpcb_2024_imputed.dtypes)

print("\n2025 data types:")
print(cpcb_2025_imputed.dtypes)

2024 shape: (8784, 13)
2025 shape: (8760, 13)

2024 data types:
timestamp          datetime64[us]
pm25                      float64
pm10                      float64
no2                       float64
so2                       float64
co                        float64
o3                        float64
temperature               float64
humidity                  float64
wind_speed                float64
wind_direction            float64
rainfall                  float64
solar_radiation           float64
dtype: object

2025 data types:
timestamp          datetime64[us]
pm25                      float64
pm10                      float64
no2                       float64
so2                       float64
co                        float64
o3                        float64
temperature               float64
humidity                  float64
wind_speed                float64
wind_direction            float64
rainfall                  float64
solar_radiation           float64
dtype: object

In [40]:
import os

os.makedirs("../data/processed", exist_ok=True)

In [41]:
cpcb_2024_imputed.to_csv(
    "../data/processed/CPCB_Ambazari_2024_cleaned.csv",
    index=False
)

cpcb_2025_imputed.to_csv(
    "../data/processed/CPCB_Ambazari_2025_cleaned.csv",
    index=False
)

print("Processed datasets saved successfully.")

Processed datasets saved successfully.

In [42]:
print(os.listdir("../data/processed"))

['CPCB_Ambazari_2024_cleaned.csv', 'CPCB_Ambazari_2025_cleaned.csv']

In [43]:
weather_clean = pd.read_csv("../data/raw/Weather/open-meteo-21.12N79.02E323m.csv", skiprows=2)

weather_clean.head()

,time,temperature_2m (°C),relative_humidity_2m (%),weather_code (wmo code),wind_speed_10m (km/h),wind_direction_10m (°)
0,2024-01-01T00:00,21.2,58,0,7.2,177
1,2024-01-01T01:00,20.2,61,0,3.7,11
2,2024-01-01T02:00,16.9,79,0,7.6,31
3,2024-01-01T03:00,15.4,89,0,6.5,360
4,2024-01-01T04:00,15.0,92,0,6.2,7

In [44]:
weather_clean.shape

(17544, 6)

In [46]:
weather_clean = weather_clean.rename(columns={
    "time": "timestamp",
    "temperature_2m (°C)": "temperature_weather",
    "relative_humidity_2m (%)": "humidity_weather",
    "weather_code (wmo code)": "weather_code",
    "wind_speed_10m (km/h)": "wind_speed_weather_kmh",
    "wind_direction_10m (°)": "wind_direction_weather"
})

weather_clean["timestamp"] = pd.to_datetime(
    weather_clean["timestamp"]
)

print(weather_clean["timestamp"].dtype)
print(weather_clean["timestamp"].min())
print(weather_clean["timestamp"].max())

weather_clean.head()

datetime64[us]
2024-01-01 00:00:00
2025-12-31 23:00:00

,timestamp,temperature_weather,humidity_weather,weather_code,wind_speed_weather_kmh,wind_direction_weather
0,2024-01-01 00:00:00,21.2,58,0,7.2,177
1,2024-01-01 01:00:00,20.2,61,0,3.7,11
2,2024-01-01 02:00:00,16.9,79,0,7.6,31
3,2024-01-01 03:00:00,15.4,89,0,6.5,360
4,2024-01-01 04:00:00,15.0,92,0,6.2,7

In [47]:
print("Missing weather values:")
print(weather_clean.isnull().sum())
print("Duplicate weather timestamps:", weather_clean["timestamp"].duplicated().sum())

Missing weather values:
timestamp                 0
temperature_weather       0
humidity_weather          0
weather_code              0
wind_speed_weather_kmh    0
wind_direction_weather    0
dtype: int64
Duplicate weather timestamps: 0

In [48]:
print("Negative temperature:",
      (weather_clean["temperature_weather"] < 0).sum())

print("Invalid humidity:",
      ((weather_clean["humidity_weather"] < 0) |
       (weather_clean["humidity_weather"] > 100)).sum())

print("Negative wind speed:",
      (weather_clean["wind_speed_weather_kmh"] < 0).sum())

print("Invalid wind direction:",
      ((weather_clean["wind_direction_weather"] < 0) |
       (weather_clean["wind_direction_weather"] > 360)).sum())

Negative temperature: 0
Invalid humidity: 0
Negative wind speed: 0
Invalid wind direction: 0

In [ ]:
weather_clean["wind_speed"] = (weather_clean["wind_speed_weather_kmh"] / 3.6)

weather_clean = weather_clean.drop(columns=["wind_speed_weather_kmh"])

In [51]:
weather_clean.to_csv(
    "../data/processed/OpenMeteo_Nagpur_2024_2025_cleaned.csv",
    index=False
)

print("Cleaned weather dataset saved successfully.")

Cleaned weather dataset saved successfully.

In [52]:
print(weather_clean.shape)
print(weather_clean.columns)
print(weather_clean.isnull().sum())

(17544, 6)
Index(['timestamp', 'temperature_weather', 'humidity_weather', 'weather_code',
       'wind_direction_weather', 'wind_speed'],
      dtype='str')
timestamp                 0
temperature_weather       0
humidity_weather          0
weather_code              0
wind_direction_weather    0
wind_speed                0
dtype: int64